### ISSUE TITLE
Expand panel border color

### ISSUE THREAD

**Issue by NavCore** [alexander-makarov/ExpandCollapsePanel#4]
Hello there!

I'm very pleased with your ExpandCollapsePanel! It's great =)

Is there any way we can change panel border color?

Thanks

**Comment by alexander-makarov** [comment]
Hello, NavCore! 
Yeah, sure! Though there is no such property provided right away for Panel (or for ExpandCollapsePanel), it might be quite easily done, please take a look on http://stackoverflow.com/a/28105725 or https://vicky4147.wordpress.com/2007/03/04/how-to-draw-a-custom-border-around-a-form-or-control/. Feel free to write me a note or reopen the issue if you have any problems implementing it, i would try to help.

**Comment by NavCore** [comment]
Thanks, that works like a charm ;) cheers

**Comment by bhaveshsorathiya1** [comment]
Thanks.
